# Generated by Django 3.2.5 on 2021-07-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profile_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=30)),
                ('lastPrice', models.FloatField(default=0)),
                ('currentPrice', models.FloatField(default=0)),
            ],
        ),
    ]
