# Generated by Django 3.2.5 on 2021-08-26 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20210807_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastIP',
            field=models.CharField(default='0.0.0.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiringTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 19, 41, 34, 737551)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewStart',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 19, 41, 34, 737551)),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='timeToNextUpdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 19, 41, 34, 737551, tzinfo=utc)),
        ),
    ]
