# Generated by Django 3.2.5 on 2021-08-26 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20210826_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastCity',
            field=models.CharField(default='Buttigliera', max_length=35),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastCountry',
            field=models.CharField(default='Italy', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiringTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 19, 47, 8, 406072)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewStart',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 19, 47, 8, 406072)),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='timeToNextUpdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 19, 47, 8, 406072, tzinfo=utc)),
        ),
    ]
