# Generated by Django 3.2.5 on 2021-07-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isPublic',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
