# Generated by Django 3.2.5 on 2021-07-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.IntegerField(default=10),
        ),
    ]
