# Generated by Django 3.2.5 on 2021-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210726_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='openbids',
            name='vote',
            field=models.IntegerField(choices=[(1, 'UP'), (-1, 'DOWN')], default=1),
        ),
    ]
