# Generated by Django 3.2.5 on 2021-08-04 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_openbids_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expiringTime',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='hasView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='viewStart',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
