# Generated by Django 3.2.5 on 2021-08-04 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210804_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiringTime',
            field=models.TimeField(default=datetime.datetime(2021, 8, 4, 11, 30, 42, 478569)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewStart',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 11, 30, 42, 478569)),
        ),
    ]
