# Generated by Django 3.2.5 on 2021-08-04 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210804_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expiringTime',
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewStart',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 11, 48, 8, 754958)),
        ),
    ]
