# Generated by Django 3.2.5 on 2021-08-04 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210804_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expiringTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 11, 49, 57, 961717)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewStart',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 11, 49, 57, 961717)),
        ),
    ]
