# Generated by Django 3.2.5 on 2021-08-04 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210804_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeToNextUpdate', models.TimeField(default=datetime.time(13, 45, 39, 37315))),
                ('creditsForTimeSlotView', models.IntegerField(default=10)),
                ('TimeSlotDuration', models.IntegerField(default=10)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiringTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 13, 45, 39, 37315)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewStart',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 13, 45, 39, 37315)),
        ),
    ]
