# Generated by Django 3.2.5 on 2021-08-04 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210804_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiringTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 13, 53, 29, 190446)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewStart',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 13, 53, 29, 190446)),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='timeToNextUpdate',
            field=models.TimeField(default=datetime.time(13, 53, 29, 190446)),
        ),
    ]
