# Generated by Django 3.2.5 on 2021-08-04 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210804_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='TimeSlotDuration',
            new_name='timeSlotDuration',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondsToAPIRequest',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiringTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 14, 19, 28, 545771)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewStart',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 14, 19, 28, 545771)),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='timeToNextUpdate',
            field=models.TimeField(default=datetime.time(14, 19, 28, 545771)),
        ),
    ]
